# Generated by Django 6.0.3 on 2026-05-06 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
